# the URL of the target
target: http://localhost:8080

# format used for coverage
#coverage_format: jacoco

# Optional total fuzzing time-out in seconds.
timeout: 30

# If present, ask the coverage monitor to generate a report after the time-out passes.
report: true

# Must be one of {'json', 'human-readable'}
output_format: human-readable

## CHANGE TO YOUR OWN PATHS:

# The path to the open api specification of the target.
openapi_spec: openapi.json

# Where is the coverage host running, can be either a hostname or an IP address. Must include a port.
#coverage_host: localhost:6300

# When generating a coverage report, look for source files in this directory
#source_dir: "/my_directory/src/main/java"

# When generating a Jacoco coverage report, look for class files in this directory.
#jacoco_class_dir: "/my_directory/target"


## ADDITIONAL OPTIONAL FIELDS:

## Must be one of {'off', 'error', 'warn', 'info', 'debug', 'trace'}
# log_level: info

## Per-request time-out in milliseconds. Defaults to 30 seconds.
# request_timeout: 30000

## If present, reproduces the crash given an input file, then quits.
# reproduce: test_request.yml

## How to log in to the API server, if applicable. See login.md.
# authentication: auth.yml

## Prefix used to filter the classes returned from the jacoco coverage.
# jacoco_class_prefix: "org/example/software/class"
